# GENERAL PARAMETERS
general:
  chromosome_n : 50  # Must be even integer
  generation_n : 600

# CROSSOVER PARAMETERS
crossover:
  crossover_p : 0.95

# SELECTION PARAMETERS
selection:
  elite_p           : 0.2
  truncation_p      : 0.2
  truncation_amount : 0.5  # Must be 0.5 at this point in time

# MUTATION PARAMETERS
mutation:
  rate : 0.1
